export const AllCatMenuItems= [
    {
      id: 0,
      link: "/categories",
      cate: "Arts and Culture",
    //   menu: Data.Agriculture,
    },
    {
      id: 1,
      link: "/categories",
      cate: "Beauty and Personal Cares",
    //   menu: Data.foodAndBeverages,
    },
    {
      id: 2,
      link: "/categories",
      cate: "Agriculture",
    //   menu: Data.ConsumerElectonics,
    },
    {
      id: 3,
      link: "/categories",
      cate: "Home Appliances",
    //   menu: Data.HomeAppliances,
    },
    {
      id: 4,
      link: "/categories",
      cate: "Appreal",
    //   menu: Data.Appreal,
    },
    {
      id: 5,
      link: "/categories",
      cate: "Fashion Accessories",
    //   menu: Data.FashionAccessories,
    },
    {
      id: 6,
      link: "/categories",
      cate: "Home and Garden",
    //   menu: Data.HomeAndGarden,
    },
    {
      id: 7,
      link: "/categories",
      cate: "Furniture",
    //   menu: Data.Furniture,
    },
    {
      id: 8,
      link: "/categories",
      cate: "Energy",
    //   menu: Data.Energy,
    },
    {
      id: 9,
      link: "/categories",
      cate: "Enviroment",
    //   menu: Data.Enviroment,
    },
    {
      id: 10,
      link: "/categories",
      cate: "Machinery",
    //   menu: Data.Machinery,
    },
    {
      id: 11,
      link: "/categories",
      cate: "Vehicles and Accessories",
    //   menu: Data.VehiclesAndAccesories,
    },
    {
      id: 12,
      link: "/categories",
      cate: "Business Services",
    //   menu: Data.BusinessServices,
    },
    {
      id: 13,
      link: "/categories",
      cate: "Service Equipment",
    //   menu: Data.ServicesEquipment,
    },
    {
      id: 14,
      link: "/categories",
      cate: "Sports and Entertainment",
    //   menu: Data.SportsAndEntertainment,
    },
    {
      id: 15,
      link: "/categories",
      cate: "Toys and Hobbies",
    //   menu: Data.ToysAndHobbies,
    },
    {
      id: 16,
      link: "/categories",
      cate: "Packaging and Printing",
    //   menu: Data.PackagingandPrinting,
    },
    {
      id: 17,
      link: "/categories",
      cate: "Office and School Supplies",
    //   menu: Data.OfficeAndSchoolSupplies,
    },
    {
      id: 18,
      link: "/categories",
      cate: "Beauty and Personal Care",
    //   menu: Data.BeautyAndPersonalCare,
    },
    {
      id: 19,
      link: "/categories",
      cate: "Health and Medical",
    //   menu: Data.OfficeAndSchoolSupplies,
    },
    {
      id: 20,
      link: "/categories",
      cate: "Luggage, Bags and Cases",
    //   menu: Data.Luggage,
    },
    {
      id: 21,
      link: "/categories",
      cate: "Shoes and Accessories",
    //   menu: Data.ShoesAndAccesories,
    },
    {
      id: 22,
      link: "/categories",
      cate: "Minerals and Metallurgy ",
    //   menu: Data.Minerals,
    },
    {
      id: 23,
      link: "/categories",
      cate: "Rubber and Plastics",
    //   menu: Data.RubberAndPlastics,
    },
  ]